# AUTOGENERATED! DO NOT EDIT! File to edit: nbdev_nbs/speclib/decoy_library.ipynb (unless otherwise specified).

__all__ = ['DecoyProvider', 'decoy_provider']

# Cell
class DecoyProvider(object):
    def __init__(self):
        self.decoy_dict = {}

    def register(self, name, decoy_class):
        self.decoy_dict[name.lower()] = decoy_class

    def get_decoy(self, name,
        target_lib, fix_C_term=True
    )->DecoyLib:
        return self.decoy_dict[name.lower()](
            target_lib, fix_C_term
        )

decoy_provider = DecoyProvider()
decoy_provider.register('reverse', DecoyLib)
decoy_provider.register('diann', DiaNNDecoyLib)