# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbdev_nbs/spectral_library/flat_library.ipynb.

# %% auto 0
__all__ = ['FlatSpecLib']

# %% ../../nbdev_nbs/spectral_library/flat_library.ipynb 1
from alphabase.spectral_library.library_base import (
    SpecLibBase
)

# %% ../../nbdev_nbs/spectral_library/flat_library.ipynb 2
class FlatSpecLib:
    def __init__(self):
        pass

    def parse_base_library(library:SpecLibBase):
        pass
