# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbdev_nbs/spectral_library/library_reader.ipynb.

# %% auto 0
__all__ = ['LibraryReaderBase']

# %% ../../nbdev_nbs/spectral_library/library_reader.ipynb 3
import typing
import numpy as np
import pandas as pd

from ..peptide.mobility import mobility_to_ccs_for_df
from ..io.psm_reader.dia_search_reader import SpectronautReader
from .library_base import SpecLibBase
from ..psm_reader.psm_reader import psm_reader_yaml

# %% ../../nbdev_nbs/spectral_library/library_reader.ipynb 4
class LibraryReaderBase(SpecLibBase):
    '''
    Read library information (precursors and fragments)
    '''
    def __init__(self,
        *,
        charged_frag_types:typing.List[str] = [
            'b_z1','b_z2','y_z1', 'y_z2', 
            'b_modloss_z1','b_modloss_z2',
            'y_modloss_z1', 'y_modloss_z2'
        ],
        precursor_mz_min:float = 400,
        precursor_mz_max:float = 2000,
        decoy:str = None,
        **kwargs,
    ):
        super().__init__(
            charged_frag_types,
            precursor_mz_min=precursor_mz_min,
            precursor_mz_max=precursor_mz_max,
            decoy=decoy
        )
