# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbdev_nbs/scoring/feature_extraction_base.ipynb.

# %% auto 0
__all__ = ['BaseFeatureExtractor']

# %% ../../nbdev_nbs/scoring/feature_extraction_base.ipynb 2
import pandas as pd

# %% ../../nbdev_nbs/scoring/feature_extraction_base.ipynb 3
class BaseFeatureExtractor:
    def __init__(self):
        self._feature_list = ['score','nAA','charge']

    @property
    def feature_list(self)->list:
        """
        This is a property. It tells ML scoring modules 
        what features (columns) are extracted by 
        this FeatureExtractor for scoring.

        Returns
        -------
        list
            feature names (columns) in the PSM dataframe
        """

        self._feature_list = list(set(self._feature_list))
        return self._feature_list

    def extract_features(self, 
        psm_df:pd.DataFrame, 
        *args, **kwargs
    )->pd.DataFrame:
        """
        Extract the scoring features (self._feature_list) 
        and append them inplace into candidate PSMs (psm_df).

        **All sub-classes must re-implement this method.**

        Parameters
        ----------
        psm_df : pd.DataFrame
            PSMs to be rescored

        Returns
        -------
        pd.DataFrame
            psm_df with appended feature columns extracted by this extractor
        """
        return psm_df

