# AUTOGENERATED! DO NOT EDIT! File to edit: nbdev_nbs/io/psm_reader/maxquant_reader.ipynb (unless otherwise specified).

__all__ = ['parse_mod_seq', 'MaxQuantReader']

# Cell
import pandas as pd
import numba

from alphabase.io.psm_reader.psm_reader import (
    PSMReaderBase, psm_reader_provider
)

@numba.njit
def parse_mod_seq(
    modseq,
    mod_sep='()',
    fixed_C=True,
    underscore_for_ncterm=True,
):
    PeptideModSeq = modseq
    mod_list = []
    site_list = []
    site = PeptideModSeq.find(mod_sep[0])
    while site != -1:
        site_end = PeptideModSeq.find(mod_sep[1],site+1)+1
        if site_end < len(PeptideModSeq) and PeptideModSeq[site_end] == mod_sep[1]:
            site_end += 1
        if underscore_for_ncterm: site_list.append(str(site-1))
        else: site_list.append(str(site))
        start_mod = site
        if start_mod > 0: start_mod -= 1
        mod_list.append(PeptideModSeq[start_mod:site_end])
        PeptideModSeq = PeptideModSeq[:site] + PeptideModSeq[site_end:]
        site = PeptideModSeq.find(mod_sep[0], site)
    if fixed_C:
        site = PeptideModSeq.find('C')
        while site != -1:
            if underscore_for_ncterm: site_list.append(str(site))
            else: site_list.append(str(site+1))
            mod_list.append('C'+"Carbamidomethyl (C)".join(mod_sep))
            site = PeptideModSeq.find('C',site+1)
    return ';'.join(mod_list), ';'.join(site_list)


class MaxQuantReader(PSMReaderBase):
    def __init__(self,
        *,
        column_mapping:dict = None,
        modification_mapping:dict = None,
        fdr = 0.01,
        keep_decoy = False,
        mod_sep = '()',
        underscore_for_ncterm=True,
        fixed_C57 = True,
        mod_seq_column='Modified sequence',
        **kwargs,
    ):
        super().__init__(
            column_mapping=column_mapping,
            modification_mapping=modification_mapping,
            fdr = fdr,
            keep_decoy = keep_decoy,
        )

        self.mod_sep = mod_sep
        self.underscore_for_ncterm=underscore_for_ncterm
        self.fixed_C = fixed_C57
        self.mod_seq_column = mod_seq_column

    def _init_modification_mapping(self):
        self.modification_mapping = {
            'Acetyl@Protein N-term':
                [
                    '_(Acetyl (Protein N-term))',
                    '_(ac)','_(UniMod:1)'
                ],
            'Carbamidomethyl@C':
                [
                    'C(Carbamidomethyl (C))',
                    'C(UniMod:4)'
                ],
            'Oxidation@M':
                [
                    'M(Oxidation (M))',
                    'M(ox)', 'M(UniMod:35)'
                ],
            'Phospho@S':
                [
                    'S(Phospho (S))',
                    'S(Phospho (ST))',
                    'S(Phospho (STY))',
                    'S(ph)',
                    'S(UniMod:21)'
                ],
            'Phospho@T':
                [
                    'T(Phospho (T))',
                    'T(Phospho (ST))',
                    'T(Phospho (STY))',
                    'T(ph)',
                    'T(UniMod:21)'
                ],
            'Phospho@Y':
                [
                    'Y(Phospho (Y))',
                    'Y(Phospho (STY))',
                    'Y(ph)',
                    'Y(UniMod:21)'
                ],
            'Deamidated@N': ['N(Deamidation (NQ))'],
            'Deamidated@Q': ['Q(Deamidation (NQ))'],
            'GlyGly@K': ['K(GlyGly (K))', 'K(gl)'],
        }

    def set_modification_mapping(self, modification_mapping: dict):
        if modification_mapping is None:
            self._init_modification_mapping()
        else:
            self.modification_mapping = modification_mapping
        self._extend_mod_brackets()
        self._reverse_mod_mapping()

    def _extend_mod_brackets(self):
        for key, mod_list in list(self.modification_mapping.items()):
            self.modification_mapping[key].extend(
                [
                    f'{mod[0]}[{mod[2:-1]}]'
                    if mod[1] == '(' else f'{mod[0]}({mod[2:-1]})'
                    for mod in mod_list
                ]
            )
            self.modification_mapping[key].extend(
                [f'{mod[1:]}' for mod in mod_list if mod.startswith('_')]
            )

    def _init_column_mapping(self):
        self.column_mapping = {
            'sequence': 'Sequence',
            'charge': 'Charge',
            'rt': 'Retention time',
            'ccs': 'CCS',
            'mobility': ['Mobility','IonMobility'],
            'spec_idx': ['Scan number','MS/MS scan number','Scan index'],
            'raw_name': 'Raw file',
            'precursor_mz': 'm/z',
            'score': 'Score',
            'proteins': 'Proteins',
            'genes': ['Gene Names','Gene names'],
            'decoy': 'decoy',
            'fdr': 'fdr',
        }

    def _load_file(self, filename):
        df = pd.read_csv(filename, sep='\t')
        df = df[~pd.isna(df['Retention time'])]
        df.fillna('', inplace=True)
        if 'K0' in df.columns:
            df['Mobility'] = df['K0'] # Bug in MaxQuant, it should be 1/K0
        # min_rt = df['Retention time'].min()
        # df['rt_norm'] = (
        #     df['Retention time']-min_rt
        # )/(df['Retention time'].max()-min_rt)
        df['decoy'] = 0
        df.loc[df['Reverse']=='+','decoy'] == 1
        return df

    def _load_modifications(self, origin_df: pd.DataFrame):
        (
            self._psm_df['mods'],
            self._psm_df['mod_sites']
        ) = zip(
            *origin_df[self.mod_seq_column].apply(
                parse_mod_seq, mod_sep=self.mod_sep,
                fixed_C=self.fixed_C,
                underscore_for_ncterm=self.underscore_for_ncterm
            )
        )

psm_reader_provider.register_reader('maxquant', MaxQuantReader)