# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"reset_AA_mass": "aa.ipynb",
         "ret_set_AA_df": "aa.ipynb",
         "AA_CHEM": "aa.ipynb",
         "AA_ASCII_MASS": "aa.ipynb",
         "AA_DF": "aa.ipynb",
         "get_sequence_mass": "aa.ipynb",
         "get_AA_masses_for_same_len_seqs": "aa.ipynb",
         "get_sequence_masses_for_same_len_seqs": "aa.ipynb",
         "get_sequence_array_mass": "aa.ipynb",
         "truncate_isotope": "element.ipynb",
         "reset_elements": "element.ipynb",
         "load_elem_yaml": "element.ipynb",
         "MAX_ISOTOPE_LEN": "element.ipynb",
         "EMPTY_DIST": "element.ipynb",
         "MASS_PROTON": "element.ipynb",
         "MASS_ISOTOPE": "element.ipynb",
         "parse_formula": "element.ipynb",
         "calc_formula_mass": "element.ipynb",
         "abundance_convolution": "element.ipynb",
         "one_element_dist": "element.ipynb",
         "formula_dist": "element.ipynb",
         "load_mod_yaml": "modification.ipynb",
         "load_modloss_importance": "modification.ipynb",
         "get_modification_mass": "modification.ipynb",
         "get_modification_mass_sum": "modification.ipynb",
         "get_modloss_mass": "modification.ipynb",
         "get_charged_frag_types": "fragment.ipynb",
         "parse_charged_frag_type": "fragment.ipynb",
         "get_by_and_peptide_mass": "fragment.ipynb",
         "get_peptide_mass_for_same_len_seqs": "fragment.ipynb",
         "get_by_and_peptide_mass_for_same_len_seqs": "fragment.ipynb",
         "init_zero_fragment_dataframe": "fragment.ipynb",
         "init_fragment_dataframe_from_other": "fragment.ipynb",
         "init_fragment_by_precursor_dataframe": "fragment.ipynb",
         "set_sliced_fragment_dataframe": "fragment.ipynb",
         "get_sliced_fragment_dataframe": "fragment.ipynb",
         "concat_precursor_fragment_dataframes": "fragment.ipynb",
         "get_fragment_mass_dataframe": "fragment.ipynb",
         "set_precursor_mz": "fragment.ipynb",
         "DecoyLib": "decoy_library.ipynb",
         "DiaNNDecoyLib": "decoy_library.ipynb",
         "DecoyLibProvider": "decoy_library.ipynb",
         "decoy_lib_provider": "decoy_library.ipynb",
         "SpecLibBase": "library_base.ipynb",
         "load_yaml": "yaml_utils.ipynb",
         "save_yaml": "yaml_utils.ipynb"}

modules = ["constants/aa.py",
           "constants/element.py",
           "constants/modification.py",
           "peptide/fragment.py",
           "speclib/decoy_library.py",
           "speclib/library_base.py",
           "yaml_utils.py"]

doc_url = "https://MannLabs.github.io/alphabase/"

git_url = "https://github.com/MannLabs/alphabase/tree/main/"

def custom_doc_links(name): return None
