# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"reset_AA_mass": "aa.ipynb",
         "ret_set_AA_df": "aa.ipynb",
         "AA_CHEM": "aa.ipynb",
         "AA_ASCII_MASS": "aa.ipynb",
         "AA_DF": "aa.ipynb",
         "get_sequence_mass": "aa.ipynb",
         "get_same_len_sequences_mass": "aa.ipynb",
         "get_sequence_array_mass": "aa.ipynb",
         "truncate_isotope": "element.ipynb",
         "reset_parameters": "element.ipynb",
         "CHEM_INFO_DICT": "element.ipynb",
         "CHEM_MONO_MASS": "element.ipynb",
         "CHEM_ISOTOPE_DIST": "element.ipynb",
         "MAX_ISOTOPE_LEN": "element.ipynb",
         "EMPTY_DIST": "element.ipynb",
         "CHEM_MONO_IDX": "element.ipynb",
         "MASS_H2O": "element.ipynb",
         "MASS_NH3": "element.ipynb",
         "MASS_PROTON": "element.ipynb",
         "MASS_ISOTOPE": "element.ipynb",
         "parse_formula": "element.ipynb",
         "calc_formula_mass": "element.ipynb",
         "abundance_convolution": "element.ipynb",
         "one_element_dist": "element.ipynb",
         "formula_dist": "element.ipynb",
         "load_mod_yaml": "modification.ipynb",
         "load_modloss_importance": "modification.ipynb",
         "get_modification_mass": "modification.ipynb",
         "get_modloss_mass": "modification.ipynb",
         "load_yaml": "yaml_utils.ipynb",
         "save_yaml": "yaml_utils.ipynb"}

modules = ["constants/aa.py",
           "constants/element.py",
           "constants/modification.py",
           "yaml_utils.py"]

doc_url = "https://MannLabs.github.io/alphabase/"

git_url = "https://github.com/MannLabs/alphabase/tree/main/"

def custom_doc_links(name): return None
