# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbdev_nbs/yaml_utils.ipynb.

# %% auto 0
__all__ = ['load_yaml', 'save_yaml']

# %% ../nbdev_nbs/yaml_utils.ipynb 2
import yaml

def load_yaml(filename)->dict:
    with open(filename) as f:
        settings = yaml.load(f, Loader=yaml.FullLoader)
    return settings

def save_yaml(filename, settings):
    with open(filename, "w") as file:
        yaml.dump(settings, file)
